import { motion } from "framer-motion";
import {
  Brain,
  Sparkles,
  TrendingUp,
  ShieldAlert,
  Clock3,
  Building2,
  CheckCircle2,
} from "lucide-react";

export default function TrackingAIInsights() {
  // Mock AI Analysis
  // Replace with Gemini/OpenAI API later

  const aiData = {
    confidence: 96,
    probability: 92,
    eta: "16 July 2026",
    escalation: "Low",
    department: "Municipal Corporation",
    recommendation:
      "The complaint is progressing normally. No escalation is required at this stage. Field inspection is expected within the next few hours.",
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 25 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="
        rounded-3xl
        border
        border-white/10
        bg-slate-900
        p-8
        shadow-xl
      "
    >
      {/* Header */}

      <div className="flex items-center gap-5">

        <div
          className="
            flex
            h-16
            w-16
            items-center
            justify-center
            rounded-2xl
            bg-gradient-to-br
            from-violet-500
            to-cyan-500
          "
        >
          <Brain
            size={32}
            className="text-white"
          />
        </div>

        <div>

          <h2 className="text-3xl font-black text-white">
            AI Insights
          </h2>

          <p className="mt-2 text-slate-400">
            Smart prediction generated by CitizenConnect AI
          </p>

        </div>

      </div>

      {/* AI Cards */}

      <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-4">

        {/* Resolution */}

        <div className="rounded-2xl bg-slate-950 p-6">

          <div className="flex items-center gap-3">

            <TrendingUp
              size={20}
              className="text-cyan-400"
            />

            <span className="text-slate-400">
              Resolution Chance
            </span>

          </div>

          <h3 className="mt-4 text-3xl font-black text-cyan-400">
            {aiData.probability}%
          </h3>

        </div>

        {/* Confidence */}

        <div className="rounded-2xl bg-slate-950 p-6">

          <div className="flex items-center gap-3">

            <Sparkles
              size={20}
              className="text-yellow-400"
            />

            <span className="text-slate-400">
              AI Confidence
            </span>

          </div>

          <h3 className="mt-4 text-3xl font-black text-yellow-400">
            {aiData.confidence}%
          </h3>

        </div>

        {/* ETA */}

        <div className="rounded-2xl bg-slate-950 p-6">

          <div className="flex items-center gap-3">

            <Clock3
              size={20}
              className="text-emerald-400"
            />

            <span className="text-slate-400">
              Predicted Resolution
            </span>

          </div>

          <h3 className="mt-4 text-xl font-black text-emerald-400">
            {aiData.eta}
          </h3>

        </div>

        {/* Escalation */}

        <div className="rounded-2xl bg-slate-950 p-6">

          <div className="flex items-center gap-3">

            <ShieldAlert
              size={20}
              className="text-red-400"
            />

            <span className="text-slate-400">
              Escalation Risk
            </span>

          </div>

          <h3 className="mt-4 text-3xl font-black text-red-400">
            {aiData.escalation}
          </h3>

        </div>

      </div>

      {/* Department */}

      <div className="mt-8 rounded-3xl bg-slate-950 p-6">

        <div className="flex items-center gap-4">

          <Building2
            size={24}
            className="text-cyan-400"
          />

          <div>

            <p className="text-slate-400">
              Responsible Department
            </p>

            <h3 className="mt-1 text-2xl font-bold text-white">
              {aiData.department}
            </h3>

          </div>

        </div>

      </div>

      {/* Recommendation */}

      <div
        className="
          mt-8
          rounded-3xl
          border
          border-emerald-500/20
          bg-emerald-500/10
          p-6
        "
      >

        <div className="flex items-start gap-4">

          <CheckCircle2
            size={26}
            className="mt-1 text-emerald-400"
          />

          <div>

            <h3 className="text-xl font-bold text-white">
              AI Recommendation
            </h3>

            <p className="mt-3 leading-7 text-slate-300">
              {aiData.recommendation}
            </p>

          </div>

        </div>

      </div>

      {/* AI Notice */}

      <div className="mt-6 rounded-2xl border border-cyan-500/20 bg-cyan-500/10 p-5">

        <p className="text-sm leading-6 text-slate-300">
          🤖 These insights are generated using AI and historical complaint
          patterns. Actual resolution times may vary depending on workload,
          field conditions, and department response.
        </p>

      </div>

    </motion.div>
  );
}